"""Binary protocol for the ATMOS WG1000 local WebSocket."""

from pyatmos_wg1000.protocol.catalog import Device, Hod16, Id33, ParamKind, hod16_id, hod33_id, pack_register_id
from pyatmos_wg1000.protocol.data import (
    AC16_EMPTY_TEXT_ID,
    AC16_OWN_TEXT_OFFSET,
    AC16_TEXT_INDEX,
    InfoChunk,
    InfoDump,
    InfoItem,
    InfoRowType,
    TextLookup,
    assemble_info_chunks,
    decode_info_chunk,
    decode_own_text,
    encode_data_request,
    expand_info_value,
    expand_info_value_with,
    resolve_text_id,
)
from pyatmos_wg1000.protocol.enums import (
    Channel,
    CommandCode,
    DataKind,
    FileOp,
    LoginAction,
    LoginRole,
    ParamAccess,
    ParamType,
)
from pyatmos_wg1000.protocol.files import FileChunk, decode_file_chunk, encode_file_ack, encode_file_request
from pyatmos_wg1000.protocol.frame import (
    Command,
    Frame,
    decode_client_frame,
    decode_server_frame,
    encode_client_frame,
    encode_server_frame,
)
from pyatmos_wg1000.protocol.login import LoginResult, encode_login, parse_login_result
from pyatmos_wg1000.protocol.params import (
    AcdDate,
    AcdTime,
    ParamRecord,
    SetpointPair,
    decode_acd_date,
    decode_acd_quantity,
    decode_acd_temperature,
    decode_acd_time,
    decode_packed_setpoints,
    decode_param_read,
    decode_param_write_result,
    encode_param_read,
    encode_param_write,
)

__all__ = [
    "AC16_EMPTY_TEXT_ID",
    "AC16_OWN_TEXT_OFFSET",
    "AC16_TEXT_INDEX",
    "AcdDate",
    "AcdTime",
    "Channel",
    "Command",
    "CommandCode",
    "DataKind",
    "Device",
    "FileChunk",
    "FileOp",
    "Frame",
    "Hod16",
    "Id33",
    "InfoChunk",
    "InfoDump",
    "InfoItem",
    "InfoRowType",
    "LoginAction",
    "LoginResult",
    "LoginRole",
    "ParamAccess",
    "ParamKind",
    "ParamRecord",
    "ParamType",
    "SetpointPair",
    "TextLookup",
    "assemble_info_chunks",
    "decode_acd_date",
    "decode_acd_quantity",
    "decode_acd_temperature",
    "decode_acd_time",
    "decode_client_frame",
    "decode_file_chunk",
    "decode_info_chunk",
    "decode_own_text",
    "decode_packed_setpoints",
    "decode_param_read",
    "decode_param_write_result",
    "decode_server_frame",
    "encode_client_frame",
    "encode_data_request",
    "encode_file_ack",
    "encode_file_request",
    "encode_login",
    "encode_param_read",
    "encode_param_write",
    "encode_server_frame",
    "expand_info_value",
    "expand_info_value_with",
    "hod16_id",
    "hod33_id",
    "pack_register_id",
    "parse_login_result",
    "resolve_text_id",
]
