"""Binary protocol for the ATMOS WG1000 local WebSocket."""

from pyatmos.protocol.catalog import Device, Hod16, Id33, ParamKind, hod16_id, hod33_id, pack_register_id
from pyatmos.protocol.enums import Channel, CommandCode, FileOp, LoginAction, LoginRole, ParamAccess, ParamType
from pyatmos.protocol.files import FileChunk, decode_file_chunk, encode_file_ack, encode_file_request
from pyatmos.protocol.frame import (
    Command,
    Frame,
    decode_client_frame,
    decode_server_frame,
    encode_client_frame,
    encode_server_frame,
)
from pyatmos.protocol.login import LoginResult, encode_login, parse_login_result
from pyatmos.protocol.params import (
    AcdDate,
    AcdTime,
    ParamRecord,
    SetpointPair,
    decode_acd_date,
    decode_acd_quantity,
    decode_acd_temperature,
    decode_acd_time,
    decode_packed_setpoints,
    decode_param_read,
    decode_param_write_result,
    encode_param_read,
    encode_param_write,
)

__all__ = [
    "AcdDate",
    "AcdTime",
    "Channel",
    "Command",
    "CommandCode",
    "Device",
    "FileChunk",
    "FileOp",
    "Frame",
    "Hod16",
    "Id33",
    "LoginAction",
    "LoginResult",
    "LoginRole",
    "ParamAccess",
    "ParamKind",
    "ParamRecord",
    "ParamType",
    "SetpointPair",
    "decode_acd_date",
    "decode_acd_quantity",
    "decode_acd_temperature",
    "decode_acd_time",
    "decode_client_frame",
    "decode_file_chunk",
    "decode_packed_setpoints",
    "decode_param_read",
    "decode_param_write_result",
    "decode_server_frame",
    "encode_client_frame",
    "encode_file_ack",
    "encode_file_request",
    "encode_login",
    "encode_param_read",
    "encode_param_write",
    "encode_server_frame",
    "hod16_id",
    "hod33_id",
    "pack_register_id",
    "parse_login_result",
]
